### ISSUE TITLE
Running Exercise1~3 on Windows with local runner will fail with InvalidPathException exception

### ISSUE THREAD

**Issue by yafengguo** [eljefe6a/beamexample#8]
When I running Excercise1 to Excercise 3 with local runner in Intellij it will fail with below error stack:
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.nio.file.InvalidPathException: Illegal char <*> at index 23: output/user_score-temp-*
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:279)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:72)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:182)
	at org.apache.beam.examples.tutorial.game.solution.Exercise1.main(Exercise1.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.nio.file.InvalidPathException: Illegal char <\*> at index 23: output/user_score-temp-\*
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at org.apache.beam.sdk.util.FileIOChannelFactory.specToFile(FileIOChannelFactory.java:64)
	at org.apache.beam.sdk.util.FileIOChannelFactory.match(FileIOChannelFactory.java:72)
	at org.apache.beam.sdk.io.FileBasedSink$FileBasedWriteOperation.removeTemporaryFiles(FileBasedSink.java:483)
	at org.apache.beam.sdk.io.FileBasedSink$FileBasedWriteOperation.finalize(FileBasedSink.java:411)
	at org.apache.beam.sdk.io.Write$Bound$2.processElement(Write.java:417)
Looks program generated a file name which contains "*" and which is not acceptable for windows file system.
And Excerise4, Excerise5 run smoothly with expected result.

**Comment by yafengguo** [comment]
This should be related to https://issues.apache.org/jira/browse/BEAM-863

Sorry for the confusion made.
